### ISSUE TITLE
Xamarin porting

### ISSUE THREAD

**Issue by mpiffari** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#100]
Hello folks,
is there a porting of Device Manager core for DFU OTA through BLE based on SMP, in Xamarin Forms?
I've found a porting only for secure DFU based on DFU Service with UUID 0xFE59 (and characteristcs 0x8EC90001-F315-4F60-9FB8-838830DAEA50 and 0x8EC90002-F315-4F60-9FB8-838830DAEA50) (https://github.com/Laerdal/Laerdal.Dfu).

**Comment by dinesharjani** [comment]
No @mpiffari we're not supporting Xamarin ourselves. It's also not planned as of now.
