### ISSUE TITLE
How to use shell manager with iOS?

### ISSUE THREAD

**Issue by varunkudalkar** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#103]
In Android example, we can use shell commands using shell manager but I didn't find any shell manager class here in iOS, is there any way we can implement this?

**Comment by dinesharjani** [comment]
Hello @varunkudalkar - what do you mean by shell manager? Do you mean sending / receiving SMP Commands?

**Comment by varunkudalkar** [comment]
Hello @dinesharjani - Yes I was looking for the same a few months back, then I managed to write the code for the same and completed the task.

**Comment by dinesharjani** [comment]
You can do SMP commands from the Example app. Anyway, happy you were able to solve this.
