### ISSUE TITLE
FS Manager failure when downloading a file that is being appended to

### ISSUE THREAD

**Issue by MikeSnyder360** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#105]
I'm trying to download a logfile that's growing.
In this case, we're missing the ==, as the offset never matches the size, but exceeds it.

https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/blob/2fcdf9a5b20e6ab0c2215cec37ed3f26c0888126/Source/Managers/FileSystemManager.swift#L407

**Comment by dinesharjani** [comment]
Closing since https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/pull/107 was merged to fix the issue.
