### ISSUE TITLE
sendTimeout error while the device is still swapping images after image upload

### ISSUE THREAD

**Issue by maahinberiLW** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#130]
Hi,
I am getting a sendTimeout error and upgrade failed while the device is still rebooting and swapping images. I am using TestAndConfirm mode and since upgradeDidFail is called after this timeout, when the device powers on again, FirmwareUpgradeManager does not confirm the image.

The upgrade works fine in v1.3.0, but fails in 1.3.1, 1.3.2 and 1.3.3

Setting a value for estimatedSwapTime in the upload configuration in v1.3.3 also fixes this issue, however that then means that the iOS device doesn't try to reconnect till the estimated time has elapsed, even if the NRF device has already booted after image swap.

Is there a way to set the send timeout value manually? Am I missing something here?

**Comment by dinesharjani** [comment]
The 'estimatedSwapTime' use you mention is correct, that's what it's there for. We cannot predict how long the firmware takes to do the swap - you have more information, so you can set the swap time appropriately.
