### ISSUE TITLE
Which McuManager repo is the fork under active development?

### ISSUE THREAD

**Issue by philltran** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#15]
The readme at https://github.com/JuulLabs-OSS/mcumgr-ios states to use this fork.

> DEPRECATED
> 
> This repository is deprecated and no longer maintained, please use the following forks:
> 
> iOS: NordicSemiconductor/IOS-nRF-Connect-Device-Manager
> Android: NordicSemiconductor/Android-nRF-Connect-Device-Manager

However the readme in the IOS-nRF-Connect-Device-Manager repo says to contribute at https://github.com/JuulLabs-OSS/mcumgr-ios. Which repo is the correct one?

> The underlying library, as of now, is 1 to 1 copy of the original. All PRs should be submitted to the original repository.

Also, if this is the repo moving forward, I will make an issue to update [the podspec ](https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/blob/master/McuManager.podspec) to reference this repo.

**Comment by philips77** [comment]
Hello,
It is this repo (nRF Connect Device Manager) that is maintained. We're working on a new version, which should be released soon. We already fixed the readme in this project.
