### ISSUE TITLE
Is it possible to check the existence of a file using FileSystemManager?

### ISSUE THREAD

**Issue by MarkBorazio** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#20]
I need to be able to tell if a file exists or not.

To test this out, I am currently trying to use the `FileSystemManager` to download a file that I know does not exist. I am getting an error back, but it is simply returning `FileTransferError.mcuMgrErrorCode(McuMgrReturnCode.unknown)`.

Is `McuMgrReturnCode.unknown` an accurate way to determine if a file is non-existent? [I can see that the sample code in this repository considers this to be true](https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/blob/master/Example/Example/View%20Controllers/Manager/FileDownloadViewController.swift#L98), but the fact that it is simply an `unknown` error code makes me doubt that.

**Comment by philips77** [comment]
This is what we've discovered during testing. Have a look at:
https://github.com/zephyrproject-rtos/zephyr/blob/8889114e3ca907fcd928d7addd0bdde92fa18f51/subsys/mgmt/mcumgr/lib/cmd/fs_mgmt/src/fs_mgmt.c#L65
The first call is to get file length. The implementation of this method is here:
https://github.com/zephyrproject-rtos/zephyr/blob/8889114e3ca907fcd928d7addd0bdde92fa18f51/subsys/mgmt/mcumgr/lib/cmd/fs_mgmt/src/zephyr_fs_mgmt.c#L12
That method returns `.unknown` in case the file has not been found.
