### ISSUE TITLE
Incompatible dependencies - ZIPFoundation

### ISSUE THREAD

**Issue by nysander** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#251]
```
[!] CocoaPods could not find compatible versions for pod "ZIPFoundation":
  In snapshot (Podfile.lock):
    ZIPFoundation (= 0.9.19)

  In Podfile:
    iOSDFULibrary (= 4.15.3) was resolved to 4.15.3, which depends on
      ZIPFoundation (= 0.9.19)

    iOSMcuManagerLibrary (= 1.7.0) was resolved to 1.7, which depends on
      ZIPFoundation (= 0.9.11)
      ```

**Comment by MalcolmnDEV** [comment]
![Screenshot 2024-07-15 at 15 15 19](https://github.com/user-attachments/assets/cbab11ea-9c7e-40e2-a597-c41035698447)
I get a similar issue using SPM

**Comment by nysander** [comment]
what about cocoapods?

**Comment by dinesharjani** [comment]
hmm, can you make a pull request for cocoapods ?

**Comment by dinesharjani** [comment]
I'll try to do it. Fingers crossed it's a simple version bump

**Comment by dinesharjani** [comment]
@nysander we'd have to raise minimum deployment version to 12.0, looks like.

**Comment by nysander** [comment]
for us it's not a problem we support 14.0+ but we use your dfu and smp libraries in paralel for different devices so having dependencies aligned is important for us.

thanks for update in advance

**Comment by dinesharjani** [comment]
Alright. I'll make a PR with a branch for you to test it out.

**Comment by dinesharjani** [comment]
Pull Request: https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/pull/254

**Comment by nysander** [comment]
pod update and build successful

**Comment by dinesharjani** [comment]
Merged
