### ISSUE TITLE
Regression 1.1.0 -> 1.2.1/1.2.2/1.2.3/1.2.4: Bad Header received. Maybe packet size is smaller than minimum header size?

### ISSUE THREAD

**Issue by t3zeng** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#51]
Running mynewt OS and seeing a regression in reading image list on version 1.2.1 and 1.2.2. 

Repro:
1. Run a device with image slot 0 and image slot 1 and connect using nrf connect device manager
2. In the Image tab at the top right, press advanced and then press read to observe the error

Image Upload feature still works but due to the image read failure the test and confirm process cannot be done on the app.
nrf connect dfu still works and is capable of doing all of the steps, the issue is just with the device manager app.

Image list can also still be read using:
`newtmgr image list -c <conn-name>`

Problem seems to go away if only one image slot is loaded rather than two. I changed the internal flash address of image slot 1 and the error goes away but only reads back the image from image slot 0

**Comment by RickGroenewegen** [comment]
I'm running into the same issue. Running the following:

`dfuManager.start(images: package.images, using: dfuManagerConfiguration`

Results into 'Bad Header received. Maybe packet size is smaller than minimum header size?' after the state changes from 'upload' to 'test'

Error seems to be on line 123 of McuMgrBleTransport+CBPeripheralDelegate

**Comment by t3zeng** [comment]
Regular nRF Connect App is now also broken with this issue as of 2.5.2

**Comment by philips77** [comment]
@RickGroenewegen @t3zeng do you have logs? I'm interested in what data are received in the notification that fails.
The check seems to be here:
https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/blob/b55deaaf23b97e7efebb7576b55ef10c9652f21b/Source/McuMgrHeader.swift#L101-L104

Should shorter notification be ignored? What does it contain?

**Comment by RickGroenewegen** [comment]
The notification seems to be 3 bytes, which is smaller than McuMgrHeader.HEADER_LENGTH to it returns nil and throws the bad header error.

How would you like me to check what the notification contains? I'm quite new to Swift, but would like to help out.

**Comment by dinesharjani** [comment]
Ah. Maybe this is an easy fix. (Maybe.)
I'll have a look in a couple of minutes.

**Comment by philips77** [comment]
@dinesharjani I think it can be ignored.
However, mind that you may also need to reassemble long packets (SMP reassembly on mobile side). If you'd get a header with length greater than number of bytes in the notification, buffer then and wait until all are received. That may be the root cause for this as well, if the tx MTU is low, and data are sent in multiple notifications from the device.

**Comment by dinesharjani** [comment]
Update: We believe root cause is found. I will do all I can to release today. Otherwise it'll be tomorrow.

**Comment by t3zeng** [comment]
Looks like I am able to read image data again as of 1.2.5 😄 @RickGroenewegen give it a try

**Comment by dinesharjani** [comment]
Going to close as majority of users report it has been fixed.
