### ISSUE TITLE
Upgrade successful but upgradeDidComplete does not fire

### ISSUE THREAD

**Issue by RickGroenewegen** [NordicSemiconductor/IOS-nRF-Connect-Device-Manager#69]
I'm able to fully upgrade the firmware using this library.

However, upgradeDidComplete does not fire. Instead I'm getting an error:

`2022-08-01 11:39:46.160235+0200 App[4548:292971] [CoreBluetooth] XPC connection invalid`

However, when I comment line 252 in FirmwareUpgradeManager it does work. Line 252 sets the cyclicReferenceHolder to nil:

`cyclicReferenceHolder = nil`

Seems like the reference is removed too quickly or something for upgradeDidComplete to finish?

**Comment by scsonic** [comment]
the mcumgr in android will fire Complete
but the ios not, same error here

**Comment by scsonic** [comment]
Thansk Rick's informations
finally, my solution is 
```
DispatchQueue.main.async { [weak self] in
    self?.delegate?.upgradeDidComplete()
    self?.cyclicReferenceHolder = nil
}
```

**Comment by RickGroenewegen** [comment]
Thanks scsonic! 

I've created a PR: 

https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/pull/72

**Comment by dinesharjani** [comment]
PR was merged. Closing for now.
